### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by PStewart1**
added functionality for printing % symbol, as well as function descriptions.

### CODE REVIEW

**Comment by PStewart1** [comment]
fixed the count of chars printed, added 'd' and 'i' functionality, and separated _puts and _putchar into their own files.

**Comment by PStewart1** [comment]
got rid of extra spaces, and made it pretty for betty, but we'll have to separate out some of it out into separate functions, as it's too long. Still, it works very well right now.

**Comment by PStewart1** [comment]
separated some functionality out into its own function, cutting down on the lines to under 40. also replaced the switch case with some if-else statements. and cleaned up the test file. Now passes Betty!

**Comment by CalebHouse99** [comment]
Great work Paul

**Pull request merged**
